version: '3.8'

services:
  webserver:
    image: eklovya333/nginx-image3:latest
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - webapp
  nodejs:
    image: node-image1:latest
    container_name: node-app
    environment:
      port: 3000
    ports:
      - "3000:3000"
    networks:
      - webapp

networks:
  webapp:
    driver: bridge